# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx  
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
---       

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:   
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

